### PR TITLE
Use opening php tag for new files

### PR DESCRIPTION
**Pull request by Forage**
For new files, a php opening tag should be at the top of the file. People appear to be overlooking this, resulting in unclear errors when testing at the end of the tutorial.

Sorry for the commit mess, I tried to make it easier for you, but I ended up with a series of commits in the process.

### CODE REVIEW

**Comment by geerteltink** [comment]
Same as PR #23

**Comment by Forage** [comment]
It's indeed a duplicate. I don't tend to check all closed PR's.

I disagree with it being overkill or too much noise though. I've seen different people running into the problem, including me. Yes, programmers should be aware of it, but going through a tutorial, not checking if the site works after each step, and having to go back through all the steps again after spending a long time finding the problem to begin with is more distracting from what you are trying to tell then having a simple opening tag from the start.

At least be consistent and use it everywhere or nowhere at all.

**Comment by froschdesign** [comment]
> People appear to be overlooking this, resulting in unclear errors when testing at the end of the tutorial.

Use an IDE and you will never have this problem.

**Comment by Forage** [comment]
No point in keeping this open when having different views on tutorial quality.

**Pull request closed without merging**
